### PR TITLE
Make it possibly to supply a custom gdb executable path

### PR DESCRIPTION
**Pull request by xyproto**
* Add a `NewCustom` function, to be able to use ie. `rust-gdb` as the executable.

### CODE REVIEW

**Comment by cyrus-and** [comment]
Thank you, but there's no need to duplicate the code.

**Comment by xyproto** [comment]
Thanks, the new changes looks good.

Btw, if the fields in the `Gdb` struct were exported, then the same thing would have been possible without a `NewCustom` function. Have you considered exporting them?

```go
// Gdb represents a GDB instance. It implements the ReadWriter interface to
// read/write data from/to the target program's TTY.
type Gdb struct {
	io.ReadWriter

	ptm *os.File
	pts *os.File
	cmd *exec.Cmd

	mutex  sync.RWMutex
	stdin  io.WriteCloser
	stdout io.ReadCloser

	sequence int64
	pending  map[string]chan map[string]interface{}

	onNotification NotificationCallback

	recordReaderDone chan bool
}
```

**Comment by cyrus-and** [comment]
Better use the `New*` pattern alone IMHO.

**Comment by xyproto** [comment]
Another btw: I'm using `gdb` in [o](https://github.com/xyproto/o) and it works great for C and C++. Thanks for making this package in the first place. :slightly_smiling_face: :+1:

**Pull request closed without merging**
